### ISSUE TITLE
🐛 "Perfil dev"

### ISSUE THREAD

**Issue by DiogoLCarvalho** [Mais-Jogos/MaisJogosFrontendReact#3]
O Estilo da página de Perfil dev ficou zuada.

**Comment by DiogoLCarvalho** [comment]
Consegui arrumar. Não sei porque mas tudo tinha ficado em binário 😅

**Comment by Aryel15** [comment]
Eu peguei uma outra versão e troquei no meu local, é estranho isso as vezes acontece do nada
